-- +goose Up
-- ops_health_snapshots: periodic health metric snapshots generated by OpsAgent.
-- Each snapshot contains all metric categories as JSONB for flexible querying.
CREATE TABLE ops_health_snapshots (
    id          TEXT PRIMARY KEY,
    snapshot    JSONB NOT NULL DEFAULT '{}',
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ops_health_snapshots_captured_at ON ops_health_snapshots(captured_at DESC);

-- ops_alert_rules: configurable thresholds that trigger alerts.
CREATE TABLE ops_alert_rules (
    id          TEXT PRIMARY KEY,
    metric_name TEXT NOT NULL,
    operator    TEXT NOT NULL CHECK (operator IN ('GT', 'LT', 'DEVIATION')),
    threshold   REAL NOT NULL,
    severity    TEXT NOT NULL CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    channel     TEXT NOT NULL CHECK (channel IN ('SLACK', 'PAGERDUTY', 'BOTH')),
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_ops_alert_rules_metric_name ON ops_alert_rules(metric_name);

-- ops_alerts: fired alert history with acknowledgement tracking.
CREATE TABLE ops_alerts (
    id               TEXT PRIMARY KEY,
    rule_id          TEXT NOT NULL REFERENCES ops_alert_rules(id),
    metric_name      TEXT NOT NULL,
    current_value    REAL NOT NULL,
    threshold        REAL NOT NULL,
    severity         TEXT NOT NULL CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    channel          TEXT NOT NULL CHECK (channel IN ('SLACK', 'PAGERDUTY', 'BOTH')),
    fired_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    acknowledged_at  TIMESTAMPTZ,
    acknowledged_by  TEXT REFERENCES users(id)
);

CREATE INDEX idx_ops_alerts_rule_id ON ops_alerts(rule_id);
CREATE INDEX idx_ops_alerts_fired_at ON ops_alerts(fired_at DESC);
CREATE INDEX idx_ops_alerts_severity ON ops_alerts(severity);
CREATE INDEX idx_ops_alerts_acknowledged ON ops_alerts(acknowledged_at) WHERE acknowledged_at IS NULL;

-- +goose Down
DROP INDEX IF EXISTS idx_ops_alerts_acknowledged;
DROP INDEX IF EXISTS idx_ops_alerts_severity;
DROP INDEX IF EXISTS idx_ops_alerts_fired_at;
DROP INDEX IF EXISTS idx_ops_alerts_rule_id;
DROP TABLE IF EXISTS ops_alerts;
DROP INDEX IF EXISTS idx_ops_alert_rules_metric_name;
DROP TABLE IF EXISTS ops_alert_rules;
DROP INDEX IF EXISTS idx_ops_health_snapshots_captured_at;
DROP TABLE IF EXISTS ops_health_snapshots;
