// Package agreement implements the AgreementAgent: AI-powered item-specific
// clause generation merged into an immutable base agreement template.
package agreement

import (
	"encoding/json"
	"errors"
	"time"
)

// Sentinel errors.
var (
	ErrAgreementNotFound = errors.New("agreement not found")
	ErrAlreadyAccepted   = errors.New("agreement already accepted by this user")
	ErrNotParty          = errors.New("user is not a party to this agreement")
)

// ClauseCategory classifies what an item-specific clause governs.
type ClauseCategory string

const (
	ClauseCategoryUseRestriction  ClauseCategory = "USE_RESTRICTION"
	ClauseCategoryCareRequirement ClauseCategory = "CARE_REQUIREMENT"
	ClauseCategoryDamageDefinition ClauseCategory = "DAMAGE_DEFINITION"
	ClauseCategorySafety          ClauseCategory = "SAFETY"
)

// Clause is a single item-specific term generated by the AI.
type Clause struct {
	Title    string         `json:"title"`
	Text     string         `json:"text"`
	Category ClauseCategory `json:"category"`
}

// baseSection is one section of the base agreement template JSON.
type baseSection struct {
	ID      string  `json:"id"`
	Title   string  `json:"title"`
	Text    string  `json:"text,omitempty"`
	Dynamic bool    `json:"dynamic,omitempty"`
	Source  string  `json:"source,omitempty"`
	Clauses []Clause `json:"clauses,omitempty"`
}

// baseTemplate is the parsed structure of base_template_v{N}.json.
type baseTemplate struct {
	Version       string        `json:"version"`
	EffectiveDate string        `json:"effective_date"`
	Sections      []baseSection `json:"sections"`
}

// Agreement is the stored agreement for a transaction.
type Agreement struct {
	ID                string
	TransactionID     string
	Version           string
	FullAgreement     json.RawMessage
	CustomClauses     json.RawMessage
	PromptVersion     *string
	Model             *string
	GuardrailWarnings json.RawMessage
	CreatedAt         time.Time
}

// Acceptance records a single party's agreement acceptance.
type Acceptance struct {
	ID          string
	AgreementID string
	UserID      string
	AcceptedAt  time.Time
	IPAddress   *string
	DeviceID    *string
}

// AcceptanceStatus summarises which parties have accepted.
type AcceptanceStatus struct {
	AgreementID    string    `json:"agreementId"`
	TransactionID  string    `json:"transactionId"`
	HostAccepted   bool      `json:"hostAccepted"`
	RenterAccepted bool      `json:"renterAccepted"`
	BothAccepted   bool      `json:"bothAccepted"`
	HostAcceptedAt *time.Time `json:"hostAcceptedAt,omitempty"`
	RenterAcceptedAt *time.Time `json:"renterAcceptedAt,omitempty"`
}

// AgreementResponse is the JSON payload for GET /api/v1/transactions/:id/agreement.
type AgreementResponse struct {
	ID            string          `json:"id"`
	TransactionID string          `json:"transactionId"`
	Version       string          `json:"version"`
	FullAgreement json.RawMessage `json:"fullAgreement"`
	CustomClauses json.RawMessage `json:"customClauses"`
	CreatedAt     time.Time       `json:"createdAt"`
}

// AcceptRequest is the JSON body for POST /api/v1/transactions/:id/agreement/accept.
type AcceptRequest struct {
	DeviceID string `json:"deviceId"`
}

// agreementPromptData is the template data for the agreement/v{N}.txt prompt.
type agreementPromptData struct {
	ItemName            string
	Category            string
	EstimatedValueCents int
	ConditionNotes      string
}

// clauseAIResult is the structured JSON response from the AI.
type clauseAIResult struct {
	Clauses []Clause `json:"clauses"`
}
